/*
 * Copyright (c) 2025 The ZMK Contributors
 *
 * SPDX-License-Identifier: MIT
 */

#pragma once

#include <zephyr/sys/util.h>

#define ZMK_BATTERY_CPF_TO_NAME_0 "Unknown"
#define ZMK_BATTERY_CPF_TO_NAME_1 "First"
#define ZMK_BATTERY_CPF_TO_NAME_2 "Second"
#define ZMK_BATTERY_CPF_TO_NAME_3 "Third"
#define ZMK_BATTERY_CPF_TO_NAME_4 "Fourth"
#define ZMK_BATTERY_CPF_TO_NAME_5 "Fifth"
#define ZMK_BATTERY_CPF_TO_NAME_6 "Sixth"
#define ZMK_BATTERY_CPF_TO_NAME_7 "Seventh"
#define ZMK_BATTERY_CPF_TO_NAME_8 "Eighth"
#define ZMK_BATTERY_CPF_TO_NAME_9 "Ninth"
#define ZMK_BATTERY_CPF_TO_NAME_10 "Tenth"
#define ZMK_BATTERY_CPF_TO_NAME_11 "Eleventh"
#define ZMK_BATTERY_CPF_TO_NAME_12 "Twelfth"
#define ZMK_BATTERY_CPF_TO_NAME_13 "Thirteenth"
#define ZMK_BATTERY_CPF_TO_NAME_14 "Fourteenth"
#define ZMK_BATTERY_CPF_TO_NAME_15 "Fifteenth"
#define ZMK_BATTERY_CPF_TO_NAME_16 "Sixteenth"
#define ZMK_BATTERY_CPF_TO_NAME_17 "Seventeenth"
#define ZMK_BATTERY_CPF_TO_NAME_18 "Eighteenth"
#define ZMK_BATTERY_CPF_TO_NAME_19 "Nineteenth"
#define ZMK_BATTERY_CPF_TO_NAME_20 "Twentieth"
#define ZMK_BATTERY_CPF_TO_NAME_21 "Twenty first"
#define ZMK_BATTERY_CPF_TO_NAME_22 "Twenty second"
#define ZMK_BATTERY_CPF_TO_NAME_23 "Twenty third"
#define ZMK_BATTERY_CPF_TO_NAME_24 "Twenty fourth"
#define ZMK_BATTERY_CPF_TO_NAME_25 "Twenty fifth"
#define ZMK_BATTERY_CPF_TO_NAME_26 "Twenty sixth"
#define ZMK_BATTERY_CPF_TO_NAME_27 "Twenty seventh"
#define ZMK_BATTERY_CPF_TO_NAME_28 "Twenty eighth"
#define ZMK_BATTERY_CPF_TO_NAME_29 "Twenty ninth"
#define ZMK_BATTERY_CPF_TO_NAME_30 "Thirtieth"
#define ZMK_BATTERY_CPF_TO_NAME_31 "Thirty first"
#define ZMK_BATTERY_CPF_TO_NAME_32 "Thirty second"
#define ZMK_BATTERY_CPF_TO_NAME_33 "Thirty third"
#define ZMK_BATTERY_CPF_TO_NAME_34 "Thirty fourth"
#define ZMK_BATTERY_CPF_TO_NAME_35 "Thirty fifth"
#define ZMK_BATTERY_CPF_TO_NAME_36 "Thirty sixth"
#define ZMK_BATTERY_CPF_TO_NAME_37 "Thirty seventh"
#define ZMK_BATTERY_CPF_TO_NAME_38 "Thirty eighth"
#define ZMK_BATTERY_CPF_TO_NAME_39 "Thirty ninth"
#define ZMK_BATTERY_CPF_TO_NAME_40 "Fortieth"
#define ZMK_BATTERY_CPF_TO_NAME_41 "Forty first"
#define ZMK_BATTERY_CPF_TO_NAME_42 "Forty second"
#define ZMK_BATTERY_CPF_TO_NAME_43 "Forty third"
#define ZMK_BATTERY_CPF_TO_NAME_44 "Forty fourth"
#define ZMK_BATTERY_CPF_TO_NAME_45 "Forty fifth"
#define ZMK_BATTERY_CPF_TO_NAME_46 "Forty sixth"
#define ZMK_BATTERY_CPF_TO_NAME_47 "Forty seventh"
#define ZMK_BATTERY_CPF_TO_NAME_48 "Forty eighth"
#define ZMK_BATTERY_CPF_TO_NAME_49 "Forty ninth"
#define ZMK_BATTERY_CPF_TO_NAME_50 "Fiftieth"
#define ZMK_BATTERY_CPF_TO_NAME_51 "Fifty first"
#define ZMK_BATTERY_CPF_TO_NAME_52 "Fifty second"
#define ZMK_BATTERY_CPF_TO_NAME_53 "Fifty third"
#define ZMK_BATTERY_CPF_TO_NAME_54 "Fifty fourth"
#define ZMK_BATTERY_CPF_TO_NAME_55 "Fifty fifth"
#define ZMK_BATTERY_CPF_TO_NAME_56 "Fifty sixth"
#define ZMK_BATTERY_CPF_TO_NAME_57 "Fifty seventh"
#define ZMK_BATTERY_CPF_TO_NAME_58 "Fifty eighth"
#define ZMK_BATTERY_CPF_TO_NAME_59 "Fifty ninth"
#define ZMK_BATTERY_CPF_TO_NAME_60 "Sixtieth"
#define ZMK_BATTERY_CPF_TO_NAME_61 "Sixty first"
#define ZMK_BATTERY_CPF_TO_NAME_62 "Sixty second"
#define ZMK_BATTERY_CPF_TO_NAME_63 "Sixty third"
#define ZMK_BATTERY_CPF_TO_NAME_64 "Sixty fourth"
#define ZMK_BATTERY_CPF_TO_NAME_65 "Sixty fifth"
#define ZMK_BATTERY_CPF_TO_NAME_66 "Sixty sixth"
#define ZMK_BATTERY_CPF_TO_NAME_67 "Sixty seventh"
#define ZMK_BATTERY_CPF_TO_NAME_68 "Sixty eighth"
#define ZMK_BATTERY_CPF_TO_NAME_69 "Sixty ninth"
#define ZMK_BATTERY_CPF_TO_NAME_70 "Seventieth"
#define ZMK_BATTERY_CPF_TO_NAME_71 "Seventy first"
#define ZMK_BATTERY_CPF_TO_NAME_72 "Seventy second"
#define ZMK_BATTERY_CPF_TO_NAME_73 "Seventy third"
#define ZMK_BATTERY_CPF_TO_NAME_74 "Seventy fourth"
#define ZMK_BATTERY_CPF_TO_NAME_75 "Seventy fifth"
#define ZMK_BATTERY_CPF_TO_NAME_76 "Seventy sixth"
#define ZMK_BATTERY_CPF_TO_NAME_77 "Seventy seventh"
#define ZMK_BATTERY_CPF_TO_NAME_78 "Seventy eighth"
#define ZMK_BATTERY_CPF_TO_NAME_79 "Seventy ninth"
#define ZMK_BATTERY_CPF_TO_NAME_80 "Eightieth"
#define ZMK_BATTERY_CPF_TO_NAME_81 "Eighty first"
#define ZMK_BATTERY_CPF_TO_NAME_82 "Eighty second"
#define ZMK_BATTERY_CPF_TO_NAME_83 "Eighty third"
#define ZMK_BATTERY_CPF_TO_NAME_84 "Eighty fourth"
#define ZMK_BATTERY_CPF_TO_NAME_85 "Eighty fifth"
#define ZMK_BATTERY_CPF_TO_NAME_86 "Eighty sixth"
#define ZMK_BATTERY_CPF_TO_NAME_87 "Eighty seventh"
#define ZMK_BATTERY_CPF_TO_NAME_88 "Eighty eighth"
#define ZMK_BATTERY_CPF_TO_NAME_89 "Eighty ninth"
#define ZMK_BATTERY_CPF_TO_NAME_90 "Ninetieth"
#define ZMK_BATTERY_CPF_TO_NAME_91 "Ninety first"
#define ZMK_BATTERY_CPF_TO_NAME_92 "Ninety second"
#define ZMK_BATTERY_CPF_TO_NAME_93 "Ninety third"
#define ZMK_BATTERY_CPF_TO_NAME_94 "Ninety fourth"
#define ZMK_BATTERY_CPF_TO_NAME_95 "Ninety fifth"
#define ZMK_BATTERY_CPF_TO_NAME_96 "Ninety sixth"
#define ZMK_BATTERY_CPF_TO_NAME_97 "Ninety seventh"
#define ZMK_BATTERY_CPF_TO_NAME_98 "Ninety eighth"
#define ZMK_BATTERY_CPF_TO_NAME_99 "Ninety ninth"
#define ZMK_BATTERY_CPF_TO_NAME_100 "One hundredth"
#define ZMK_BATTERY_CPF_TO_NAME_101 "One hundred and first"
#define ZMK_BATTERY_CPF_TO_NAME_102 "One hundred and second"
#define ZMK_BATTERY_CPF_TO_NAME_103 "One hundred and third"
#define ZMK_BATTERY_CPF_TO_NAME_104 "One hundred and fourth"
#define ZMK_BATTERY_CPF_TO_NAME_105 "One hundred and fifth"
#define ZMK_BATTERY_CPF_TO_NAME_106 "One hundred and sixth"
#define ZMK_BATTERY_CPF_TO_NAME_107 "One hundred and seventh"
#define ZMK_BATTERY_CPF_TO_NAME_108 "One hundred and eighth"
#define ZMK_BATTERY_CPF_TO_NAME_109 "One hundred and ninth"
#define ZMK_BATTERY_CPF_TO_NAME_110 "One hundred and tenth"
#define ZMK_BATTERY_CPF_TO_NAME_111 "One hundred and eleventh"
#define ZMK_BATTERY_CPF_TO_NAME_112 "One hundred and twelfth"
#define ZMK_BATTERY_CPF_TO_NAME_113 "One hundred and thirteenth"
#define ZMK_BATTERY_CPF_TO_NAME_114 "One hundred and fourteenth"
#define ZMK_BATTERY_CPF_TO_NAME_115 "One hundred and fifteenth"
#define ZMK_BATTERY_CPF_TO_NAME_116 "One hundred and sixteenth"
#define ZMK_BATTERY_CPF_TO_NAME_117 "One hundred and seventeenth"
#define ZMK_BATTERY_CPF_TO_NAME_118 "One hundred and eighteenth"
#define ZMK_BATTERY_CPF_TO_NAME_119 "One hundred and nineteenth"
#define ZMK_BATTERY_CPF_TO_NAME_120 "One hundred twentieth"
#define ZMK_BATTERY_CPF_TO_NAME_121 "One hundred and twenty first"
#define ZMK_BATTERY_CPF_TO_NAME_122 "One hundred and twenty second"
#define ZMK_BATTERY_CPF_TO_NAME_123 "One hundred and twenty third"
#define ZMK_BATTERY_CPF_TO_NAME_124 "One hundred and twenty fourth"
#define ZMK_BATTERY_CPF_TO_NAME_125 "One hundred and twenty fifth"
#define ZMK_BATTERY_CPF_TO_NAME_126 "One hundred and twenty sixth"
#define ZMK_BATTERY_CPF_TO_NAME_127 "One hundred and twenty seventh"
#define ZMK_BATTERY_CPF_TO_NAME_128 "One hundred and twenty eighth"
#define ZMK_BATTERY_CPF_TO_NAME_129 "One hundred and twenty ninth"
#define ZMK_BATTERY_CPF_TO_NAME_130 "One hundred thirtieth"
#define ZMK_BATTERY_CPF_TO_NAME_131 "One hundred and thirty first"
#define ZMK_BATTERY_CPF_TO_NAME_132 "One hundred and thirty second"
#define ZMK_BATTERY_CPF_TO_NAME_133 "One hundred and thirty third"
#define ZMK_BATTERY_CPF_TO_NAME_134 "One hundred and thirty fourth"
#define ZMK_BATTERY_CPF_TO_NAME_135 "One hundred and thirty fifth"
#define ZMK_BATTERY_CPF_TO_NAME_136 "One hundred and thirty sixth"
#define ZMK_BATTERY_CPF_TO_NAME_137 "One hundred and thirty seventh"
#define ZMK_BATTERY_CPF_TO_NAME_138 "One hundred and thirty eighth"
#define ZMK_BATTERY_CPF_TO_NAME_139 "One hundred and thirty ninth"
#define ZMK_BATTERY_CPF_TO_NAME_140 "One hundred fortieth"
#define ZMK_BATTERY_CPF_TO_NAME_141 "One hundred and forty first"
#define ZMK_BATTERY_CPF_TO_NAME_142 "One hundred and forty second"
#define ZMK_BATTERY_CPF_TO_NAME_143 "One hundred and forty third"
#define ZMK_BATTERY_CPF_TO_NAME_144 "One hundred and forty fourth"
#define ZMK_BATTERY_CPF_TO_NAME_145 "One hundred and forty fifth"
#define ZMK_BATTERY_CPF_TO_NAME_146 "One hundred and forty sixth"
#define ZMK_BATTERY_CPF_TO_NAME_147 "One hundred and forty seventh"
#define ZMK_BATTERY_CPF_TO_NAME_148 "One hundred and forty eighth"
#define ZMK_BATTERY_CPF_TO_NAME_149 "One hundred and forty ninth"
#define ZMK_BATTERY_CPF_TO_NAME_150 "One hundred fiftieth"
#define ZMK_BATTERY_CPF_TO_NAME_151 "One hundred and fifty first"
#define ZMK_BATTERY_CPF_TO_NAME_152 "One hundred and fifty second"
#define ZMK_BATTERY_CPF_TO_NAME_153 "One hundred and fifty third"
#define ZMK_BATTERY_CPF_TO_NAME_154 "One hundred and fifty fourth"
#define ZMK_BATTERY_CPF_TO_NAME_155 "One hundred and fifty fifth"
#define ZMK_BATTERY_CPF_TO_NAME_156 "One hundred and fifty sixth"
#define ZMK_BATTERY_CPF_TO_NAME_157 "One hundred and fifty seventh"
#define ZMK_BATTERY_CPF_TO_NAME_158 "One hundred and fifty eighth"
#define ZMK_BATTERY_CPF_TO_NAME_159 "One hundred and fifty ninth"
#define ZMK_BATTERY_CPF_TO_NAME_160 "One hundred sixtieth"
#define ZMK_BATTERY_CPF_TO_NAME_161 "One hundred and sixty first"
#define ZMK_BATTERY_CPF_TO_NAME_162 "One hundred and sixty second"
#define ZMK_BATTERY_CPF_TO_NAME_163 "One hundred and sixty third"
#define ZMK_BATTERY_CPF_TO_NAME_164 "One hundred and sixty fourth"
#define ZMK_BATTERY_CPF_TO_NAME_165 "One hundred and sixty fifth"
#define ZMK_BATTERY_CPF_TO_NAME_166 "One hundred and sixty sixth"
#define ZMK_BATTERY_CPF_TO_NAME_167 "One hundred and sixty seventh"
#define ZMK_BATTERY_CPF_TO_NAME_168 "One hundred and sixty eighth"
#define ZMK_BATTERY_CPF_TO_NAME_169 "One hundred and sixty ninth"
#define ZMK_BATTERY_CPF_TO_NAME_170 "One hundred seventieth"
#define ZMK_BATTERY_CPF_TO_NAME_171 "One hundred and seventy first"
#define ZMK_BATTERY_CPF_TO_NAME_172 "One hundred and seventy second"
#define ZMK_BATTERY_CPF_TO_NAME_173 "One hundred and seventy third"
#define ZMK_BATTERY_CPF_TO_NAME_174 "One hundred and seventy fourth"
#define ZMK_BATTERY_CPF_TO_NAME_175 "One hundred and seventy fifth"
#define ZMK_BATTERY_CPF_TO_NAME_176 "One hundred and seventy sixth"
#define ZMK_BATTERY_CPF_TO_NAME_177 "One hundred and seventy seventh"
#define ZMK_BATTERY_CPF_TO_NAME_178 "One hundred and seventy eighth"
#define ZMK_BATTERY_CPF_TO_NAME_179 "One hundred and seventy ninth"
#define ZMK_BATTERY_CPF_TO_NAME_180 "One hundred eightieth"
#define ZMK_BATTERY_CPF_TO_NAME_181 "One hundred and eighty first"
#define ZMK_BATTERY_CPF_TO_NAME_182 "One hundred and eighty second"
#define ZMK_BATTERY_CPF_TO_NAME_183 "One hundred and eighty third"
#define ZMK_BATTERY_CPF_TO_NAME_184 "One hundred and eighty fourth"
#define ZMK_BATTERY_CPF_TO_NAME_185 "One hundred and eighty fifth"
#define ZMK_BATTERY_CPF_TO_NAME_186 "One hundred and eighty sixth"
#define ZMK_BATTERY_CPF_TO_NAME_187 "One hundred and eighty seventh"
#define ZMK_BATTERY_CPF_TO_NAME_188 "One hundred and eighty eighth"
#define ZMK_BATTERY_CPF_TO_NAME_189 "One hundred and eighty ninth"
#define ZMK_BATTERY_CPF_TO_NAME_190 "One hundred ninetieth"
#define ZMK_BATTERY_CPF_TO_NAME_191 "One hundred and ninety first"
#define ZMK_BATTERY_CPF_TO_NAME_192 "One hundred and ninety second"
#define ZMK_BATTERY_CPF_TO_NAME_193 "One hundred and ninety third"
#define ZMK_BATTERY_CPF_TO_NAME_194 "One hundred and ninety fourth"
#define ZMK_BATTERY_CPF_TO_NAME_195 "One hundred and ninety fifth"
#define ZMK_BATTERY_CPF_TO_NAME_196 "One hundred and ninety sixth"
#define ZMK_BATTERY_CPF_TO_NAME_197 "One hundred and ninety seventh"
#define ZMK_BATTERY_CPF_TO_NAME_198 "One hundred and ninety eighth"
#define ZMK_BATTERY_CPF_TO_NAME_199 "One hundred and ninety ninth"
#define ZMK_BATTERY_CPF_TO_NAME_200 "Two hundredth"
#define ZMK_BATTERY_CPF_TO_NAME_201 "Two hundred and first"
#define ZMK_BATTERY_CPF_TO_NAME_202 "Two hundred and second"
#define ZMK_BATTERY_CPF_TO_NAME_203 "Two hundred and third"
#define ZMK_BATTERY_CPF_TO_NAME_204 "Two hundred and fourth"
#define ZMK_BATTERY_CPF_TO_NAME_205 "Two hundred and fifth"
#define ZMK_BATTERY_CPF_TO_NAME_206 "Two hundred and sixth"
#define ZMK_BATTERY_CPF_TO_NAME_207 "Two hundred and seventh"
#define ZMK_BATTERY_CPF_TO_NAME_208 "Two hundred and eighth"
#define ZMK_BATTERY_CPF_TO_NAME_209 "Two hundred and ninth"
#define ZMK_BATTERY_CPF_TO_NAME_210 "Two hundred and tenth"
#define ZMK_BATTERY_CPF_TO_NAME_211 "Two hundred and eleventh"
#define ZMK_BATTERY_CPF_TO_NAME_212 "Two hundred and twelfth"
#define ZMK_BATTERY_CPF_TO_NAME_213 "Two hundred and thirteenth"
#define ZMK_BATTERY_CPF_TO_NAME_214 "Two hundred and fourteenth"
#define ZMK_BATTERY_CPF_TO_NAME_215 "Two hundred and fifteenth"
#define ZMK_BATTERY_CPF_TO_NAME_216 "Two hundred and sixteenth"
#define ZMK_BATTERY_CPF_TO_NAME_217 "Two hundred and seventeenth"
#define ZMK_BATTERY_CPF_TO_NAME_218 "Two hundred and eighteenth"
#define ZMK_BATTERY_CPF_TO_NAME_219 "Two hundred and nineteenth"
#define ZMK_BATTERY_CPF_TO_NAME_220 "Two hundred and twentieth"
#define ZMK_BATTERY_CPF_TO_NAME_221 "Two hundred and twenty first"
#define ZMK_BATTERY_CPF_TO_NAME_222 "Two hundred and twenty second"
#define ZMK_BATTERY_CPF_TO_NAME_223 "Two hundred and twenty third"
#define ZMK_BATTERY_CPF_TO_NAME_224 "Two hundred and twenty fourth"
#define ZMK_BATTERY_CPF_TO_NAME_225 "Two hundred and twenty fifth"
#define ZMK_BATTERY_CPF_TO_NAME_226 "Two hundred and twenty sixth"
#define ZMK_BATTERY_CPF_TO_NAME_227 "Two hundred and twenty seventh"
#define ZMK_BATTERY_CPF_TO_NAME_228 "Two hundred and twenty eighth"
#define ZMK_BATTERY_CPF_TO_NAME_229 "Two hundred and twenty ninth"
#define ZMK_BATTERY_CPF_TO_NAME_230 "Two hundred and thirtieth"
#define ZMK_BATTERY_CPF_TO_NAME_231 "Two hundred and thirty first"
#define ZMK_BATTERY_CPF_TO_NAME_232 "Two hundred and thirty second"
#define ZMK_BATTERY_CPF_TO_NAME_233 "Two hundred and thirty third"
#define ZMK_BATTERY_CPF_TO_NAME_234 "Two hundred and thirty fourth"
#define ZMK_BATTERY_CPF_TO_NAME_235 "Two hundred and thirty fifth"
#define ZMK_BATTERY_CPF_TO_NAME_236 "Two hundred and thirty sixth"
#define ZMK_BATTERY_CPF_TO_NAME_237 "Two hundred and thirty seventh"
#define ZMK_BATTERY_CPF_TO_NAME_238 "Two hundred and thirty eighth"
#define ZMK_BATTERY_CPF_TO_NAME_239 "Two hundred and thirty ninth"
#define ZMK_BATTERY_CPF_TO_NAME_240 "Two hundred and fortieth"
#define ZMK_BATTERY_CPF_TO_NAME_241 "Two hundred and forty first"
#define ZMK_BATTERY_CPF_TO_NAME_242 "Two hundred and forty second"
#define ZMK_BATTERY_CPF_TO_NAME_243 "Two hundred and forty third"
#define ZMK_BATTERY_CPF_TO_NAME_244 "Two hundred and forty fourth"
#define ZMK_BATTERY_CPF_TO_NAME_245 "Two hundred and forty fifth"
#define ZMK_BATTERY_CPF_TO_NAME_246 "Two hundred and forty sixth"
#define ZMK_BATTERY_CPF_TO_NAME_247 "Two hundred and forty seventh"
#define ZMK_BATTERY_CPF_TO_NAME_248 "Two hundred and forty eighth"
#define ZMK_BATTERY_CPF_TO_NAME_249 "Two hundred and forty ninth"
#define ZMK_BATTERY_CPF_TO_NAME_250 "Two hundred and fiftieth"
#define ZMK_BATTERY_CPF_TO_NAME_251 "Two hundred and fifty first"
#define ZMK_BATTERY_CPF_TO_NAME_252 "Two hundred and fifty second"
#define ZMK_BATTERY_CPF_TO_NAME_253 "Two hundred and fifty third"
#define ZMK_BATTERY_CPF_TO_NAME_254 "Two hundred and fifty fourth"
#define ZMK_BATTERY_CPF_TO_NAME_255 "Two hundred and fifty fifth"
#define ZMK_BATTERY_CPF_TO_NAME_256 "Front"
#define ZMK_BATTERY_CPF_TO_NAME_257 "Back"
#define ZMK_BATTERY_CPF_TO_NAME_258 "Top"
#define ZMK_BATTERY_CPF_TO_NAME_259 "Bottom"
#define ZMK_BATTERY_CPF_TO_NAME_260 "Upper"
#define ZMK_BATTERY_CPF_TO_NAME_261 "Lower"
#define ZMK_BATTERY_CPF_TO_NAME_262 "Main"
#define ZMK_BATTERY_CPF_TO_NAME_263 "Backup"
#define ZMK_BATTERY_CPF_TO_NAME_264 "Auxiliary"
#define ZMK_BATTERY_CPF_TO_NAME_265 "Supplementary"
#define ZMK_BATTERY_CPF_TO_NAME_266 "Flash"
#define ZMK_BATTERY_CPF_TO_NAME_267 "Inside"
#define ZMK_BATTERY_CPF_TO_NAME_268 "Outside"
#define ZMK_BATTERY_CPF_TO_NAME_269 "Left"
#define ZMK_BATTERY_CPF_TO_NAME_270 "Right"
#define ZMK_BATTERY_CPF_TO_NAME_271 "Internal"
#define ZMK_BATTERY_CPF_TO_NAME_272 "External"

#define GET_BATTERY_DISPLAY_NAME_BY_CPF(cpf) UTIL_CAT(ZMK_BATTERY_CPF_TO_NAME_, cpf)
