manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: grandcentrix
      url-base: https://github.com/grandcentrix

  projects:
    - name: zephyr
      remote: zmkfirmware
      revision: v3.2.0+zmk-fixes
      clone-depth: 1
      import:
        name-blocklist:
          - ci-tools
          - hal_altera
          - hal_cypress
          - hal_infineon
          - hal_microchip
          - hal_nxp
          - hal_openisa
          - hal_silabs
          - hal_xtensa
          - hal_st
          - hal_ti
          - loramac-node
          - mcuboot
          - mcumgr
          - net-tools
          - openthread
          - edtt
          - trusted-firmware-m
          - sof
    - name: cobs
      repo-path: cobs
      remote: grandcentrix
      revision: 0876ef80209618b10508af728731f4944f9d2fd2
      path: modules/lib/cobs

  self:
    west-commands: scripts/west-commands.yml
