# 修改 corne_left.conf
# CONFIG_ZMK_STUDIO=n


CONFIG_ZMK_RTT_LOGGING=n

# 可选：提高日志级别（默认是 INF）
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_ZMK_LOG_LEVEL_DBG=n

CONFIG_I2C=n
# CONFIG_SPI=n
CONFIG_LOG_BUFFER_SIZE=512

CONFIG_SENSOR_LOG_LEVEL_INF=n
CONFIG_USB_DEVICE_LOG_LEVEL_INF=n


