# 修改 corne_left.conf
# CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

# 启用 RTT 作为控制台输出
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_UART_CONSOLE=y
# CONFIG_SERIAL=y
# CONFIG_USB_DEVICE_STACK=y

# CONFIG_UART_CONSOLE=y
CONFIG_ZMK_RTT_LOGGING=n

# 可选：提高日志级别（默认是 INF）
CONFIG_LOG=n
CONFIG_LOG_DEFAULT_LEVEL=2
CONFIG_ZMK_LOG_LEVEL_DBG=n

CONFIG_I2C=n
# CONFIG_SPI=n
CONFIG_LOG_BUFFER_SIZE=128

CONFIG_SENSOR_LOG_LEVEL_INF=n
CONFIG_USB_DEVICE_LOG_LEVEL_INF=n

CONFIG_OPTIMIZE_FOR_SIZE=y
CONFIG_COMPILER_OPT="-Os"
CONFIG_LTO=y

# Enable RGB underglow
CONFIG_ZMK_RGB_UNDERGLOW=n

CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=4
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MIN=4

# DO NOT CHANGE CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX TO ABOVE 80. Configuring
# BRT_MAX above 80% will draw additional current and can potentially damage your
# computer. WARRANTY IS VOID IF BRT_MAX SET ABOVE 80.
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=80

CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=285
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=75
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=16

CONFIG_ZMK_WPM=n

# CONFIG_SIZE_OPTIMIZATIONS=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# CONFIG_ZMK_DISPLAY=n