# 修改 corne_left.conf
CONFIG_ZMK_STUDIO=y

# 启用 RTT 作为控制台输出
CONFIG_UART_CONSOLE=n
CONFIG_ZMK_RTT_LOGGING=n

# 可选：提高日志级别（默认是 INF）
CONFIG_LOG=n
CONFIG_LOG_DEFAULT_LEVEL=3
# CONFIG_I2C=n
# CONFIG_SPI=n

CONFIG_OPTIMIZE_FOR_SIZE=y
CONFIG_COMPILER_OPT="-Os"
CONFIG_LTO=y


# Enable RGB underglow
CONFIG_ZMK_RGB_UNDERGLOW=y

CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=4
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MIN=4

# DO NOT CHANGE CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX TO ABOVE 80. Configuring
# BRT_MAX above 80% will draw additional current and can potentially damage your
# computer. WARRANTY IS VOID IF BRT_MAX SET ABOVE 80.
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=80

CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=285
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=75
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=16