#
# Copyright (c) 2020 The ZMK Contributors
#
# SPDX-License-Identifier: MIT
#

# ZMK Studio support build configuration for Ergodash shield
# See: https://zmk.dev/docs/features/studio#adding-zmk-studio-support-to-a-keyboard

# Example for left (central) side with Studio support
default:
  board: nice_nano_v2
  shield: ergodash_left
  snippets:
    - studio-rpc-usb-uart
  cmake-args:
    - -DCONFIG_ZMK_STUDIO=y

# Example for right side (no Studio needed)
right:
  board: nice_nano_v2
  shield: ergodash_right
