file_format: "1"
id: charybdis
name: Charybdis
type: shield
url: https://github.com/Bastardkb/Charybdis/
requires: [pro_micro]
studio: true
features:
  - keys
  - pointer
siblings:
  - charybdis_left
  - charybdis_right