/*
 * Copyright (c) 2024 The ZMK Contributors
 *
 * SPDX-License-Identifier: MIT
 */

#pragma once

#define LED_MAP_TOG_CMD 0
#define LED_MAP_ON_CMD 1
#define LED_MAP_OFF_CMD 2
#define LED_MAP_EFF_CMD 3
#define LED_MAP_EFR_CMD 4
#define LED_MAP_EFS_CMD 5
#define LED_MAP_HUI_CMD 6
#define LED_MAP_HUD_CMD 7
#define LED_MAP_SAI_CMD 8
#define LED_MAP_SAD_CMD 9
#define LED_MAP_BRI_CMD 10
#define LED_MAP_BRD_CMD 11
#define LED_MAP_SPI_CMD 12
#define LED_MAP_SPD_CMD 13
#define LED_MAP_IND_TOG_CMD 14
#define LED_MAP_IND_ON_CMD 15
#define LED_MAP_IND_OFF_CMD 16
#define LED_MAP_BAT_CMD 17
#define LED_MAP_SUB_EFF_CMD 18
#define LED_MAP_SUB_EFR_CMD 19

#define LED_MAP_TOG LED_MAP_TOG_CMD 0
#define LED_MAP_ON LED_MAP_ON_CMD 0
#define LED_MAP_OFF LED_MAP_OFF_CMD 0
#define LED_MAP_EFF LED_MAP_EFF_CMD 0
#define LED_MAP_EFR LED_MAP_EFR_CMD 0
#define LED_MAP_HUI LED_MAP_HUI_CMD 0
#define LED_MAP_HUD LED_MAP_HUD_CMD 0
#define LED_MAP_SAI LED_MAP_SAI_CMD 0
#define LED_MAP_SAD LED_MAP_SAD_CMD 0
#define LED_MAP_BRI LED_MAP_BRI_CMD 0
#define LED_MAP_BRD LED_MAP_BRD_CMD 0
#define LED_MAP_SPI LED_MAP_SPI_CMD 0
#define LED_MAP_SPD LED_MAP_SPD_CMD 0
#define LED_MAP_IND_TOG LED_MAP_IND_TOG_CMD 0
#define LED_MAP_IND_ON LED_MAP_IND_ON_CMD 0
#define LED_MAP_IND_OFF LED_MAP_IND_OFF_CMD 0
#define LED_MAP_BAT LED_MAP_BAT_CMD 0
#define LED_MAP_SUB_EFF LED_MAP_SUB_EFF_CMD 0
#define LED_MAP_SUB_EFR LED_MAP_SUB_EFR_CMD 0

/* Effect values for LED_MAP_EFS */
#define LED_MAP_EFFECT_SOLID 0
#define LED_MAP_EFFECT_BREATHE 1
#define LED_MAP_EFFECT_SPECTRUM 2
#define LED_MAP_EFFECT_SWIRL 3
#define LED_MAP_EFFECT_REACTIVE_FADE_FULL 4
#define LED_MAP_EFFECT_REACTIVE_FADE_COOL 5
#define LED_MAP_EFFECT_REACTIVE_FADE_WARM 6
#define LED_MAP_EFFECT_REACTIVE_FADE_SOLID 7
#define LED_MAP_EFFECT_ROW_WAVE_COOL 8
#define LED_MAP_EFFECT_ROW_WAVE_COOL_REV 9
#define LED_MAP_EFFECT_ROW_WAVE_WARM 10
#define LED_MAP_EFFECT_ROW_WAVE_WARM_REV 11
#define LED_MAP_EFFECT_ROW_WAVE_FULL 12
#define LED_MAP_EFFECT_ROW_WAVE_FULL_REV 13
#define LED_MAP_EFFECT_COL_WAVE_COOL 14
#define LED_MAP_EFFECT_COL_WAVE_COOL_REV 15
#define LED_MAP_EFFECT_COL_WAVE_WARM 16
#define LED_MAP_EFFECT_COL_WAVE_WARM_REV 17
#define LED_MAP_EFFECT_COL_WAVE_FULL 18
#define LED_MAP_EFFECT_COL_WAVE_FULL_REV 19
#define LED_MAP_EFFECT_STARRY 20
