import { useGSAP } from '@gsap/react';
import gsap from 'gsap';
import { type ReactNode, useRef } from 'react';

type BoardsShieldsAnimationProps = {
    children?: ReactNode;
};

const BoardsShieldsAnimation = ({ children }: BoardsShieldsAnimationProps) => {
    const rootRef = useRef<HTMLDivElement>(null);
    const svgRef = useRef<SVGSVGElement>(null);
    const yamlRef = useRef<HTMLDivElement>(null);

    useGSAP(
        () => {
            const shiftX = 120;
            const holdDuration = 1.5;
            const swapDuration = 0.2;
            const boardSelectors = ['#board0', '#board1', '#board2'];

            // Prism seems to replace the code block with a new set of elements after the initial render, so we need to query for the elements each time we swap.
            const getYamlBoardElement = (index: number) =>
                yamlRef.current?.querySelector<HTMLElement>(`.boards-shields-yaml-board${index}`) ?? null;
            const getYamlBoardElements = () => [0, 1, 2].map((index) => getYamlBoardElement(index));

            gsap.set('#board0', { x: 0, opacity: 1 });
            gsap.set('#board1', { x: shiftX, opacity: 0 });
            gsap.set('#board2', { x: shiftX, opacity: 0 });

            const yamlBoardElements = getYamlBoardElements();
            if (yamlBoardElements.some((element) => Boolean(element))) {
                gsap.set(yamlBoardElements, { display: 'none', opacity: 0, y: -10 });
                gsap.set(yamlBoardElements[0], { display: 'inline-block', opacity: 1, y: 0 });
            }

            let isActive = true;
            let currentBoardIndex = 0;
            let currentTimeline: gsap.core.Timeline | null = null;

            const playNextSwap = () => {
                if (!isActive) {
                    return;
                }

                const nextBoardIndex = (currentBoardIndex + 1) % boardSelectors.length;
                const yamlBoardElements = getYamlBoardElements();
                const fromYamlBoard = getYamlBoardElement(currentBoardIndex);
                const toYamlBoard = getYamlBoardElement(nextBoardIndex);

                currentTimeline = gsap.timeline({
                    defaults: { duration: swapDuration, ease: 'power1.inOut' },
                    onComplete: () => {
                        currentBoardIndex = nextBoardIndex;
                        playNextSwap();
                    },
                });

                currentTimeline
                    .to({}, { duration: holdDuration })
                    .set(boardSelectors[nextBoardIndex], { x: shiftX, opacity: 0 }, '>')
                    .set(toYamlBoard ?? {}, { display: 'inline-block', y: -10, opacity: 0 }, '>')
                    .to(boardSelectors[currentBoardIndex], { x: -shiftX, opacity: 0 }, '<')
                    .to(boardSelectors[nextBoardIndex], { x: 0, opacity: 1 }, '<')
                    .to(fromYamlBoard ?? {}, { y: 10, opacity: 0 }, '<')
                    .to(toYamlBoard ?? {}, { y: 0, opacity: 1 }, '<')
                    .set(yamlBoardElements, { display: 'none' }, '>')
                    .set(toYamlBoard ?? {}, { display: 'inline-block', opacity: 1, y: 0 }, '>');
            };

            playNextSwap();

            return () => {
                isActive = false;
                currentTimeline?.kill();
            };
        },
        { scope: rootRef },
    );

    return <>

        <div style={{ display: 'flex', justifyContent: 'center' }} ref={rootRef}>

            {/* Embedded font with only the few used characters, not full font. */}
            {/* Generated by Excalidraw Export SVG. */}
            {/* Excalifont licensed under OFL-1.1 */}
            {/* Note: This style and @font-face is NOT scoped, make sure there's no other Excalifont on the page */}

            <style>{`@font-face{font-family:Excalifont;src:url(data:font/woff2;base64,d09GMgABAAAAABLcAA4AAAAAIFAAABKFAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGhYbhU4cgUYGYACBFBEICq9IoxsLQAABNgIkA3wEIAWDGAcgG+4YIwP1irISIPurBG7IgNdQM8KgqpoggzPV4LvqYF1DfTjx2RKPONN4QkWr/r7haZv/3h0ctGRJGQ04cUWUNlb0utRVtvu/V9X0fFxs/7trPMgkDiyJkiComURuMskg0qT5dFovveukd92MwPatQ7aTLAEJDqpUv2nlVmpnNAJDQGBKsuB4wQsAI8376dzvn//hAP1fcBHRnr9MvUvrHzClUgU6CsiR727q7LveaXct6Vg6WBcJSG/UC1CpGKBYBAMSxljEIDak7cOKw5rRyLOwqzGAAKDCDAABEYnBBVdDFswMd3LGJAPRraOxGojujSVVQPQsaK4FIjgAgMeG61HSWCCiHqAoI+lgIyI68yAzWzjx4G9GaDwg/JsrxF64p8WLAC8a/G/kCV5hDLz2J4dwEDpPtJXhrATR4RGRkFFQT4qbgaXz8gkuADdCxKkB4RIimaoaUAKSeKnoLoCfLImhoSCAan4VhMSLgz8BwBgvAEQ3BJxGU/pRL5MkkncDNyUIA37bWIIBiRDKDZGIQVRhI+CxmDEwiB8YwlSPuxQBkrHqxFzIUUmQV2NxUeQ8YiyAXmwf2ltKuZl6sKlE3lxRqoig4sf8AMpFmSgoWM9SRyPEjzULiOo4Dw9D4GOGEaqhjCsZzjDliU3qAgCIHg+8Ap1vUBFa1H52xYGjQKFjaf1lw9cawVYFAEtWorcbo+K2lVEAcFKChuGMcEswZvZH5clHMB0Dm2huJSrUadYB/v1br/dmoq1FC0A5qAKNX4Ndd9EF5512xFhfV0diOQigh6fDC4A8UQ+eKRAAwgUASHoAkIYDVQexqhuNEkJGGBOMOwxENH603h6BQUp+eq6Vx45KCffUc7T80IF0H45NJInRxNiEslBzVqROTubJuUoy28iZyXIxZCvF9u71MiFEbsthv0Iwxj7nKw21odFSCSzOIM2WRlOt1/udrg+ATxeSV9KvfDo3mfmbiTj2AcLJgujLD0AnNKqr/ku/i7twtVlCHd12ezxfJ0Qm4+/FdWbkRpBLgFt8KkG9WE9TceNnlu3MMq1Bt9CFoeGu3ZOk5U0txorMJBhjLHKW+Fl0bv7MNEqNz8y8nx9b+yTYe9AO5Baolql3f+rRqCf32HlnDE3yvH+/vPLqkB0No47ibZrLRi4tAqLHhbXjzz9ffi86c7ip8k9iqeTd+dGZHVCQwY2sEn9U8Kw9FOxkJOW5NvNkIZJwX4Myz9eni5KQz7uBG9TbfJttNvt7uwo9QWeR8qKC5yDGiBMd4ojOeScVZSIzMxxX0lUFKwjcUTyl+5c1ADM2EDyP81SIoTW7YBt2LiVJT1qupaJz9qLYMup5zspErgo2VC7HCPtuB3J2MM7eZtlcpi1RDSGY3cx23KEaNYtn+z4drxdzI3mXV+09KIMWyP4le504lt+zw2NjLd/3zsj0BTs/9jjfdMyk8d69opOuKJJQTlWsYviSK3nC6Igs3poKJLeXAHsYddAAUF0VwdBhGzbTW4gt0AF0AbnYuRQYx9yHAE0sgk51NF1n5RXTvF8j+9MlBZW8UoP2DjF8bvZvs+t9OX6kdg8cQE+evAA/ttyIj+KXTyF+ZA8Ie4n0xzwz26y4YiRSrxg8Fx2IK1iMxSz4zn3sgcGBh3RmuO/NDALI85XFrRghDzz5L2U1kqaRVCb1jeayyqO8aicrzNgAiKqio0f5vHvM6uSc/PwwkZ/PtsExBjCGuK9kcBXCc9e8zxXsUJICg1LDqX0+/rpcb0sRnYm+DLZ0tnYX3hg5KWUzZNNXypkR0fmrQRWq9/e/F52LG1nJv9OZpQabDl9VE8G+ghBE2ML448G3f9pDeyTlp9bM9uvjz9ne9FF3zvcVD9iRK7UkdwSGP7ZYDR/6F+OsZuIuZx0Y6va8KwV5kWdM38hUuWyWyUrYlkPGhzX8CPqTmqV5VOHUnf5qBn2ABLv6zHgxQy+8MRpPRUdmJkqE/Aw1l9lpZsopfJtNLtEzkWBfqnrcUnZ+43ItPZ+q3JM9M3QfNXIzFjGOHUdMnxfDS1X7YWdWWbCra3khr0ZfOhQMDiDB3uby9aBO5DZbzgsr+fS0SwjBWMQYw0yzsglmpqIz9zSbzEoWwir/oeSTlLSK4biCCcY+IT6KG+DvaL4nuXkuBcVwL1atpr8ErYbHKYqPWY2MSSo6llVwhtx/8AVg9OVCpuNaCrtaZ19uuD2pLgiIKo2ZYWGtTMKQJy3+j1bOCqSS7rSyTPU5Heu25K61gmV+hZWX2VQoOnMWhjrmFinl/KzZVDFA+rDgBjwfik4Xqt7k63K/MK7EW7k+K67XNubu6p6kPvQVFElJvk3LXeYDAXWwPQCOANRBIEokl+cFF1ANLXiTpHzKbRlPT7CnfwuqeNVjfMjkesHl633oqD5nNTiyvi6Tfl/u7yfxKlYzTreanA9QpL8bPV7bZLp1eWyORSc7me2gGhpG70yHsbIbBG5PygUbRAB1wEMFeU0Or8L4v/uHn59/f7DLWaAj2IkkDGdnBwANwKKKfeShcyT0rGC0aK/FsEZiiDFn6SYJ5bdH8cZG/F50aiSUklzas3MEUuvwdWY6sXPCzq45a79BwygCyIOPsrmMs7Q3+aHRwmjevdcq5tPhpkCKgD2UrqQ9u2358IPzMt/f21VxBivp+3Tv3o1SB0RDCuw94GJvZW3FcY0AsvzOwwrBqroIBp0vF9Dw/7a0xvPrZsjKL6hgzz82gvoKK7ZFB3YVNLuo+08rJO2H63LIiiQkRD7zTqp7QkMehyho0B0IIU/xZv6XBAX0EHwQ7F98fXM/raUPRBLrN2r9PWgYJa6c7VvlQVpzKpmuWU3gdbRhtSeHl4nonBXxA4g3YthVvAMoGUkCGg7/s3BXdGqXp+l/b/JduVn/Ljqr4sejuAlXNTCgWRXTYYX60VO+aBzEGGss4qcfl/voa4Nq8OVPQ2Xm2Ayk1+A/GaA7HzqOtZ3Zj5y6sSuNJamEPH/OhqjwyML8nZOd9RA3cRfoFrcJG3onef8b2ye9RJ7lu3wUc4ToWzqGiBRmENdnvfooYvanFHI0c5zpYGLcHItGw8wdNQgdxIlItTfnVe8b7JhMstLy7as+bmUcj/mbMfvUmInUkaCuj/ARYxOhaxJUL668u1a8jGBlLpCnNqROOmT/Aca4vU8IsNoKWHdNnyO1V3sWCWeT0qVBG7cllwFM8ik28qaqMmfgBAqZn+Xf1hU210phmpuTHVBDxCdq3L+dk5c9E/xGb1moL9yZnCOP/h+s9VkmUgYFnZm9Y+YI4yRCLiH5+vcTYCpx9qs07qZ+zt3IzBkrJoCZk39Ypj56I162etEfPdkqyIMaqFckWsyGA5qggsYB51IV4Xd2PT31qSRjaMHA/b6vr72xGNtq8d2zs2TsRx662hm4Xjzj9LQeJ6eIFoM0JoApKt1l/e97p/pTqk2rlsZz/mmZkSkiADiyX3H2hLVT7h2bojMfMMXk4Jd5UFO2Fs1oQiCEDAwN+oxrwi9r8lLkYfEsmTLpEte4W80pFkbO2bKGseToRYSBTNVqeZP8/DBeCLCaY+wYwYE3e7bUx/x5ZCCPNKUDPU4/SkGnAieutljOvUBGWcQ73SdtAXg9cssSDd26RlpHJtsl/1idjNlHR2ZbZAwt08rab0xesLfebsW7aYzckT3er9Q6LsNWyuloc6FK0gIhY75RwilGu6I+j0R6E4NPJgpN47nOlqz+30zNJEoEchXMggPHep/da01ZzK3I6rFmWiRlTQoMaWXgkPueji+1w72GnolHjojKbUwGgOd3OsqTJ+ecZZKzX7z+5MicG+c2WGolvQBNxGaibLozpUPYnjAiWgAWad3HL6+92f4vc5clfqDZawJ2xbrkXOISKSLeiKwkz8PHQJO9dbR7gomfnBWxeeIrw8hXQY51wuhUwpPj7kqOVtA0+uXm+0r1XzhbempS9HfGDM/1/ku4ree7GaCUnRMAreTMKPG0mEdIkve+DqMxVETblbIwBVuI1bAL1dP9nLncHdEgzfnl/h+C4jqreqpeEDOADxQ0zBTdjYBtE1hNzPvmjyda+WMBBTgTBm5hqnuCVuAsd0NVdwBVVIiQxeA4dt8i0E6tvBKfwvWFvo59/sXK7giPeAKzYr7x7+ysafw4vjJLMJUej/sO8itc6zyhNqzjWbxsDcnWHOZlOKQkAm0nGKJw+t70HfW4ChEgU4pdPlGBpGyYNBRLFnNf0biVN5hzyJI3eI/xEo8pqHuE+oksYr480K001k+cE2MIyUhl9HWe6Utmuj48W+yvjicdcd5K+YuZCbJpR0UJ74oY179hztrpo3h5Xk/MfZ6lZ02avqPouY/h52Y97X7rbTiAWAesfK/7Hgu3V+EbDQRBew5YzQr549rmr1jCIAIpfnRnHPVulPdglIB2ELBgXnEci5GLDNz7JlE8xwDcGmqVWh6rNhcEpUnE5ijZ81ACp+aVsLbWwxV5os+wsn6XJ/9zmv+gWdxliIuUXKIHXqkn1aWVgxNiBO+KjjYkmLS4hAyUx9VX3/qDvqYwZjR7ZN91W6NGybk3zs1LiMdZfeyqzGdt+KaPFrIUSXqgn9bA5fylK1sG3kKi9oJfI9/D9uSAT5UhspxGvUThT1ACFEcL0gcj0Sw0C+HRf/iw8UZrd/5WCH5LNBz33kQocGbWJ+p5PM8Ijjx9iSTdF4axHA1g+rF7X6UK8upRBWymO3GWeYKuU9UBw5lpzPGCv1cCmlRMcBPSCSLpU+2p/7g1decDiMogiAT5VII14qtFjimW4EerqUysDMWcX443u0+MBi/6BuVnRkqPbzo7zEG3XkNavQqKlb57IULEkJyQS/6OvvG/0CpvFrGDIA1Fq6GTPC14txqPxGMVmiwVXB4BRrL5fbfgUAGNQKacESGUf/07eBI5MhyPusi0ANo+wqxIiDoUW1bQOvtAJ1iZr16MvO/Po3Zn5YUu/H4/3WfvR05YE3tQ0t0rW2ZGHSVmwLQj0gVaatvx5N+1g0kBQ5AiUkiSvZ25KH6RPuZlL3LDlEZpQkJAvxh93mSwAyELWaVlLEu2dnMEX4kRPS1hoYnswLiGZfaD8kjKLCk+FiUxbG8UJyr96GHQtv2iKrVOdc3suaJyRtV2mSuFlYAeg6JninJwA+dbcTjyO66i0rdis8V7rilqgqlP79xkqhkq+VhSH6yI9k7lRRqdFMvSMqhMDvSXn9rPTO62E738KJBc82Z7FZiu6qXbOfhtSipfr6TBFUv5q6Zkjcrj4EmiqREc6lrX0IlktmYSaOTRpoQPWHX37CA6GonyEDuwONgXNUbdc+nKbWaK5M/e0NaAxbHWFJEl1Fl4TozVPM5WJ+ERT/RtyA57awQ3cSw+4c3Olu+XL4z9/HpHytv0MGvuPQKzwXPYMMAxns3SnNutoXRpORGptuNXSNJthdfv2MLZ6dSjxrK95byVgV5ofakm5No2y9lVG8DIgs9OxjZ+jtPDSI7fIvpVYgh+795hGeNoqxjiwrVwNh89ezPBnN8VFutuUAwDt5oUszSe1NzwaRsH9Zy74gz3FBZdFGdVWwrIEfwR3szPI1yY3xs0n+7v+r9z3p3LaT/C48tw9oFTk4YIJMrYzsENhldIf029YOvgTbqw/qTBKhEZ2HYlftE0GRrOczXjfJRttgWjPG+KRyEhk48w2KHm9ELmbRJhA622eXn4iTQKWkRrJb8m86ZcW8Gcv17Kj3jP53zGz3h8Ln/p8sITGXdLR/Tw8r1mnLFDDuZvZYvTscIpTHB7586icPRUlLTosYSvB2tjjlOD+v3rUgbXx2WZvszK5y/1zURQ9Hgv/yh/opNLdntwD5HDN17vR+l5Szg/Q3azj3keuYz/erqTjNQHrQ8ZGcZo7dDukvqFy/xUIUFXvBOzRhgnAehg+QqLP0+r8zwG/oki+gQAAO52+NoBAODe8uddv7e7cM9w4QAgQhRVf6JMOxaT0I/O/wI9TvlSCBwzA4BHmtnHf3p4N9fADuIVCVR9RakF8CsBge1nyQy0+QmdLxTlAJ+ExIUJ9QEjrgB3gaE5BkYH4aWD4FkoJDnvfMBYdLOapC24r9yQbLnLAAOSEJx1mGEtgkwouJIAANXOjXIhjsO5CLqtuShf43Jx1Apz8QZTAyucNwAO7YoUqFahVJ1azQIkKlGmRbUCjVKVaNSkgmusECJQMLkHcPFSh3rlCb9QrYfOwLuo1o0cxse5BkVHZ/XtkrjEJV2qOha6ZmEz7nodDCpEVB4I3gL4GL3ufyFXRyE7UKFFsVgu0CawAMvM4GoKPTVNoMSoS9BaQLFIj/4TZ8N3DgAAAA==)}`}</style>

            <style>{`#animationsvg .B{font-family:Excalifont, Xiaolai, sans-serif, Segoe UI Emoji}#animationsvg .C{fill:#1e1e1e}#animationsvg .D{text-anchor:middle}#animationsvg .E{direction:ltr}#animationsvg .F{dominant-baseline:alphabetic}#animationsvg .G{font-size:16px}#animationsvg .H{stroke:#1e1e1e}#animationsvg .I{stroke-width:2}#animationsvg .J{stroke-linecap:round}`}</style>

            <svg ref={svgRef} id="animationsvg"
                xmlns="http://www.w3.org/2000/svg" viewBox="0 0 484.465 314.102" style={{ width: '100%', maxWidth: '450px', height: 'auto', display: 'block', pointerEvents: 'none' }}>
                <path d="M42 10c137.14 4.44 272.39 3.8 400.47 0 24.27 2.68 29.52 7.9 32 32 2.32 55.19 3.54 108.89 0 230.1 1.67 23.89-8.35 33.3-32 32-142.18-4.4-286.62-.67-400.47 0-17.77 2.29-35.48-7.39-32-32-4.31-47.49-1.09-96.92 0-230.1-1.84-18.97 10.47-29.76 32-32" fill="#fff" />
                <path d="M42 10h400.47M42 10h400.47m0 0c20.49.75 31.03 10.04 32 32m-32-32c19.49 2.15 31.13 8.58 32 32m0 0c-2.35 66.46.18 130.24 0 230.1m0-230.1v230.1m0 0c-.94 21.35-8.94 31.51-32 32m32-32c.79 23.56-11.98 31.13-32 32m0 0c-137.15.09-274.41-1.11-400.47 0m400.47 0H42m0 0c-19.37-.03-33.71-10.62-32-32m32 32c-23.52-.73-31.47-11.01-32-32m0 0V42m0 230.1c2.25-70.94 2.12-143.62 0-230.1m0 0c1.34-21.82 12.57-30.6 32-32M10 42c.71-21.33 12.82-31.11 32-32" fill="none" className="H I J" />

                <g id="board0">
                    <path d="M42.178 19.055c13.8-.6 32.88-.53 43.5 0 18.1 1.26 24.1 9.3 21.75 21.75 2.86 45.93-2.55 94.87 0 153.5-.51 16.52-5.46 22.38-21.75 21.75-18.41-1.21-32.87 2.48-43.5 0-16.35 1.82-21-9.57-21.75-21.75 2.05-41.29 1.36-81.55 0-153.5.25-13.03 9.93-22.27 21.75-21.75" fill="#ffec99" />
                    <path d="M42.178 19.055c12.49 1.03 26.73-.06 43.5 0m-43.5 0c9.55.15 20.62-.27 43.5 0m0 0c15.05 1.04 21.6 9.07 21.75 21.75m-21.75-21.75c15.25-2.28 19.79 8.13 21.75 21.75m0 0v153.5m0-153.5c1.76 52.56.83 102.84 0 153.5m0 0c-1.74 14.25-5.72 21.92-21.75 21.75m21.75-21.75c-.72 15.6-8.7 20.16-21.75 21.75m0 0c-14.4.38-24.99-1.84-43.5 0m43.5 0c-13.02 1.03-25.69 1.21-43.5 0m0 0c-13.42-1.4-22.98-6.42-21.75-21.75m21.75 21.75c-15.17-1.44-20.95-9.45-21.75-21.75m0 0c.93-56.87-1.57-112.56 0-153.5m0 153.5c1.38-44-.46-87.23 0-153.5m0 0c-1.81-13.02 5.37-20.18 21.75-21.75m-21.75 21.75c1.95-15.65 5.59-23.48 21.75-21.75" fill="none" className="H I J" />
                    <g transform="matrix(1 0 0 1 32.037672 97.555037)" className="B C D E F G"><text x="31.891" y="14.096">KB2040</text><text x="31.891" y="34.096">(board)</text></g>
                </g>

                <g id="board1">
                    <path d="M42.178 19.055c16.15-1.24 27.52 2.22 43.5 0 15.23.66 19.78 3.92 21.75 21.75-2.25 44.86.08 91.03 0 153.5.96 14.36-6.3 21.68-21.75 21.75-8.88 3-25.36-1.26-43.5 0-17.5 1.54-21.49-7.99-21.75-21.75-.94-64.44 3.42-118.75 0-153.5.48-16.13 7.15-18.2 21.75-21.75" fill="#ffc9c9" />
                    <path d="M42.178 19.055c10.38-2.17 20.71.18 43.5 0m-43.5 0c16.96 1.36 31.53-.37 43.5 0m0 0c14.27.5 21.37 6.89 21.75 21.75m-21.75-21.75c16.21 1.08 19.94 6.25 21.75 21.75m0 0c1.96 57.52 2.55 112.39 0 153.5m0-153.5c-2.23 40.47-.72 79.94 0 153.5m0 0c-1.3 13.82-6.31 22.88-21.75 21.75m21.75-21.75c1.66 12.21-7.1 21.44-21.75 21.75m0 0c-11.21.85-17.89-.57-43.5 0m43.5 0c-12.71.22-23.53.86-43.5 0m0 0c-13.42-.78-22.78-7.14-21.75-21.75m21.75 21.75c-13.27-.11-22.46-5.79-21.75-21.75m0 0v-153.5m0 153.5c-1.39-38.83-.43-78.58 0-153.5m0 0c-1.07-12.9 7.15-21.71 21.75-21.75m-21.75 21.75c-.23-16.7 9.42-22.73 21.75-21.75" fill="none" className="H I J" />
                    <g transform="matrix(1 0 0 1 35.196005 97.555037)" className="B C D E F G"><text x="28.732" y="14.096">mikoto</text><text x="28.732" y="34.096">(board)</text></g>
                </g>

                <g id="board2">
                    <path d="M42.178 19.055c14.63 2.34 32.92-.47 43.5 0 14.14-3.44 25.15 5.71 21.75 21.75 4.23 44.97 2.45 94.87 0 153.5.73 15.16-9.22 18.42-21.75 21.75-15.97-.85-26.8-1.14-43.5 0-13.54-.14-20.8-7.32-21.75-21.75 5.13-40.3.86-87.65 0-153.5-3-12.96 7.51-22.49 21.75-21.75" fill="#a5d8ff" />
                    <path d="M42.178 19.055h43.5m-43.5 0c15.11-.68 29.73.39 43.5 0m0 0c13.63-1.88 19.96 7.71 21.75 21.75m-21.75-21.75c16.18-1.93 19.7 8.93 21.75 21.75m0 0c-1.66 61.41-1.81 121.46 0 153.5m0-153.5v153.5m0 0c1.27 15.37-5.39 20.83-21.75 21.75m21.75-21.75c-.91 12.23-8.25 20.11-21.75 21.75m0 0c-16.41-.71-29.29 1.11-43.5 0m43.5 0c-16.32-.77-31.6-.05-43.5 0m0 0c-16.12.88-20.48-7.79-21.75-21.75m21.75 21.75c-14.95 2.06-20.1-8.42-21.75-21.75m0 0c-.26-45.4-2.37-89.12 0-153.5m0 153.5v-153.5m0 0c.14-15.15 5.85-22.09 21.75-21.75m-21.75 21.75c-.96-12.7 7.22-22.19 21.75-21.75" fill="none" className="H I J" />
                    <g transform="matrix(1 0 0 1 29.104338 97.555037)" className="B C D E F G"><text x="34.824" y="14.096">nice!nano</text><text x="34.824" y="34.096">(board)</text></g>
                </g>

                <g transform="matrix(1 0 0 1 173.666627 109.67369)" className="B C D E F"><text x="123.782" y="31.716" fontSize="36">Keyboard PCB</text><text x="123.782" y="76.716" fontSize="36">(shield)</text></g>
            </svg>

        </div>

        {/* 
            Custom highlighting class for the YAML code blocks.
            See docs/docs/concepts.mdx and docs/docusaurus.config.js for context on how this is used.
         */}
        <style>{`.boards-shields-yaml-board0, .boards-shields-yaml-board1, .boards-shields-yaml-board2{position:absolute}`}</style>
        <div ref={yamlRef}>
            {children}
        </div>

    </>;
};

export default BoardsShieldsAnimation;
